#!/usr/bin/env bash
# Generate all secrets for the self-hosted Supabase stack.
# Creates .env.docker in the project root.
#
# Usage: bash scripts/generate-keys.sh
# Re-run to regenerate keys (will overwrite .env.docker).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$ROOT_DIR/.env.docker"

echo ""
echo "🔑  Generating Supabase self-hosting keys..."
echo ""

# ── Generate JWT_SECRET ────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)

# ── Generate ANON_KEY and SERVICE_ROLE_KEY (HS256 JWTs) ───────────────────
generate_jwt() {
  local role="$1"
  python3 - "$role" "$JWT_SECRET" <<'PYEOF'
import base64, hashlib, hmac, json, sys, time

role   = sys.argv[1]
secret = sys.argv[2]
now    = int(time.time())
exp    = now + 10 * 365 * 24 * 3600  # 10 years

header  = json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":"))
payload = json.dumps(
    {"role": role, "iss": "supabase-demo", "iat": now, "exp": exp},
    separators=(",", ":"),
)

def b64url(s: str) -> str:
    return base64.urlsafe_b64encode(s.encode()).rstrip(b"=").decode()

msg = b64url(header) + "." + b64url(payload)
h   = hmac.new(secret.encode(), msg.encode(), hashlib.sha256)
sig = base64.urlsafe_b64encode(h.digest()).rstrip(b"=").decode()
print(msg + "." + sig)
PYEOF
}

ANON_KEY=$(generate_jwt "anon")
SERVICE_ROLE_KEY=$(generate_jwt "service_role")

# ── Generate POSTGRES_PASSWORD ─────────────────────────────────────────────
POSTGRES_PASSWORD=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c 24)

# ── Construct PGRST_DB_URI ─────────────────────────────────────────────────
PGRST_DB_URI="postgresql://authenticator:${POSTGRES_PASSWORD}@db:5432/postgres"

# ── Write .env.docker ──────────────────────────────────────────────────────
cat > "$OUTPUT" <<EOF
# ─────────────────────────────────────────────────────────────────────────
# Auto-generated by scripts/generate-keys.sh — DO NOT commit this file.
# Re-run the script to regenerate (will invalidate all existing sessions).
# ─────────────────────────────────────────────────────────────────────────

# Postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT (shared secret for signing tokens; used by PostgREST & Kong)
JWT_SECRET=${JWT_SECRET}

# Supabase API keys (JWTs signed with JWT_SECRET)
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# PostgREST DB connection (authenticator role, same password as Postgres)
PGRST_DB_URI=${PGRST_DB_URI}
PGRST_JWT_SECRET=${JWT_SECRET}

# Postgres Meta (for Studio)
PG_META_DB_PASSWORD=${POSTGRES_PASSWORD}

# Studio
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_KEY=${SERVICE_ROLE_KEY}
EOF

echo "✅  Created: .env.docker"
echo ""
echo "   ANON_KEY and SERVICE_ROLE_KEY written."
echo ""
echo "Next steps:"
echo "  1. Copy values into your .env.local and agent/.env:"
echo "     NEXT_PUBLIC_SUPABASE_URL=http://localhost:8000"
echo "     NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}"
echo "     SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}"
echo ""
echo "  2. docker compose up -d"
echo "  3. bash scripts/init-db.sh"
echo ""
